version: '3'
services:
  bugz_webapp:
    build: webapp
    container_name: bugz_webapp
    ports:
      - 8080:8080
    volumes:
      - ./webapp/FrontEnd:/code
    links:
      - bugz_api
  bugz_api:
    build: api
    container_name: bugz_api
    ports:
      - 8000:8000
    volumes:
      - ./api:/code
    links:
      - bugz_elasticsearch
  bugz_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: bugz_elasticsearch
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  bugz_kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    container_name: bugz_kibana
    ports:
      - 5601:5601
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: 5601
      ELASTICSEARCH_URL: http://bugz_elasticsearch:9200
      XPACK_SECURITY_ENABLED: "false"
    links:
      - bugz_elasticsearch
volumes:
  esdata: {}
