version: '3'
services:
  webapp:
    build: webapp
    container_name: webapp
    ports:
      - 8080:8080
    volumes:
      - ./webapp/FrontEnd:/code
    links:
      - api
  api:
    build: api
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./api/Bugz:/code
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_PORT: 5601
      XPACK_SECURITY_ENABLED: "false"
    links:
      - elasticsearch
volumes:
  esdata: {}
